%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Aggregate emissions by time period and by link,
% then aggregate emissions by vehicle category (LDV, LDT, MDT, HDT, PRT
%
% LDV: 1-2
% LDT: 3-6
% MDT: 7-8
% HDT: 9-16
% Ports: 17
% Author: JDS
% Date: December 9, 2014
%
% Input:  LinkEmi_i_j.csv, where i = vehicle category and j = time period
%         These emissions are generated by CalculateEmissionsV6_Pre.m
%
% Output: LDV_#.csv, LDT_#.csv, MDT_#,csv, HDT_#.csv, PRT_#.csv
%         and data in Aggregated_Emissions_NPost.xls
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear; 
clc;
diary('AggrEmisV6_NPost.txt')

load 'SegmentLink.txt';
link = unique(SegmentLink(:,2));
RFile = [pwd '\Aggregated_Emissions_NPost.xlsx'];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

mydt = datestr(now);
fprintf('Current date and time: %s \n',mydt)
fprintf('\n** Aggregating emissions by time period by vehicle category **\n');

VehCat={'LDV', 'LDT', 'MDT', 'HDT', 'PRT'}; % Name of aggregate vehicle category
VehNum={[1:2],[3:6],[7:8],[9:14,16],[17:17]}; % Mapping with MOVES categories

for iv=1:5 % Loop on vehicle categories
    tic
    s0=VehCat{iv};
    fprintf('\n* Aggregating emissions for vehicle category = %s *\n',s0);
    for j=1:96 % Loopon time periods
        VEH=zeros(size(link,1),8);
        s2=int2str(j); % time period  
        for i=1:length(VehNum{iv}) % Loop on vehicle types within a category
            s1=int2str(VehNum{iv}(i)); % vehicle type
            s3=strcat('LinkEmi_',s1,'_',s2,'.csv'); % name of file with emissions
            checkfile = exist(s3, 'file'); % Check if file 'LinkEmi_i_j' exists
            if checkfile == 0; % if the file does not exist, skip to next i
                continue
            end
            LinkEmi = load(s3);
            VEH = VEH + LinkEmi(:,2:9);
        end
        VEH(:,9)=LinkEmi(:,1); % Link number
        VEH(:,10)=LinkEmi(:,10); % Freeway (1) or arterial (0)
        VEH=VEH(:,[9,1,2,3,4,5,6,7,8,10]); % Change the order of columns
        s4=strcat(s0,'_',s2,'.csv'); % Name of file where to write results
        csvwrite(s4,VEH); % Write results
    end
    fprintf('** Finished aggregating emissions for vehicle category = %s **\n',s0);
    toc
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Aggregation by vehicle category
%
fprintf('\n** Aggregating emissions over 24 h by vehicle category and road type **\n');
tic

clearvars -except link VehCat RFile

header = {'Time_period', 'HC', 'CO', 'NOx', 'CO2atm', 'Energy', 'CO2eq', 'PM10', 'PM2.5'};
head24 = {'Veh_cat', 'HC', 'CO', 'NOx', 'CO2atm', 'Energy', 'CO2eq', 'PM10', 'PM2.5'};
colu24 = {'LDV'; 'LDT'; 'MDT'; 'HDT'; 'PRT'; 'All'};

% Preliminaries to use xlswrite1
%
fprintf('\n  Results are stored in %s\n',RFile);
warning('off','MATLAB:xlswrite:AddSheet'); % Disable Excel warning when adding new sheets

% 24 hour aggregation
%
Freeway24  = zeros(6,9); % Emissions on freeways for 24 h
Arterial24 = zeros(6,9); % Emissions on arterials for 24 h
AllRoads24 = zeros(6,9); % Emissions on all roads for 24 h

for b=1:5 % Loop on vehicle categories
    tic
    sn=VehCat{b};
    fprintf('Processing vehicle category: %s \n',sn);
    Freeway  = zeros(96,9); % Emissions on freeways for all 96 time periods
    Arterial = zeros(96,9); % Emissions on arterials for all 96 time periods
    AllRoads = zeros(96,9); % Emissions on all roads for all 96 time periods
    
    for a=1:96 % Loop on time periods
        Freeway(a,1) = a; % Time period index
        Arterial(a,1) = a; % Time period index
        AllRoads(a,1) = a; % Time period index
  
        s1=int2str(a);
        s2=strcat(sn,'_',s1,'.csv'); % Name of file that contains emissions for time period s1
        checkfile = exist(s2, 'file'); % Check if file exists
        if checkfile == 0, continue; end % if the file does not exist, skip to next i
        LinkEmi = load(s2);

        Fwy = LinkEmi(LinkEmi(:,10)==1,:); % Freeway emissions
        Freeway(a,2:9) = sum(Fwy(:,2:9));
        Art = LinkEmi(LinkEmi(:,10)==0,:); % Arterial emissions
        Arterial(a,2:9) = sum(Art(:,2:9));
        AllRoads(a,2:9) = Freeway(a,2:9) + Arterial(a,2:9); % Emissions from both
    end
    Freeway24(b,2:9)  = sum(Freeway(:,2:9)); % Sum over 24 h for each pollutant
    Arterial24(b,2:9) = sum(Arterial(:,2:9)); % Sum over 24 h for each pollutant
    AllRoads24(b,2:9) = sum(AllRoads(:,2:9)); % Sum over 24 h for each pollutant
    
    if b==1 % Sum over all vehicle categories
        FreewayAV = Freeway;
        ArterialAV = Arterial;
        AllRoadsAV = AllRoads;
    else
        FreewayAV(:,2:9)  = FreewayAV(:,2:9)  + Freeway(:,2:9);
        ArterialAV(:,2:9) = ArterialAV(:,2:9) + Arterial(:,2:9);
        AllRoadsAV(:,2:9) = AllRoadsAV(:,2:9) + AllRoads(:,2:9);       
    end
    
    sfwy=[sn,'_Fwy'];
    sart=[sn,'_Art'];
    sall=[sn,'_ARd'];
    xlswrite(RFile,header,  sfwy,'A1');
    xlswrite(RFile,Freeway, sfwy,'A2');
    xlswrite(RFile,header,  sart,'A1');
    xlswrite(RFile,Arterial,sart,'A2');
    xlswrite(RFile,header,  sall,'A1');
    xlswrite(RFile,AllRoads,sall,'A2');
    toc
end

fprintf('Writing summary results to Excel \n');

sn = 'AllVeh'; % Results for all vehicle categories
sfwy=[sn,'_Fwy'];
sart=[sn,'_Art'];
sall=[sn,'_ARd'];
xlswrite(RFile,header,    sfwy,'A1');
xlswrite(RFile,FreewayAV, sfwy,'A2');
xlswrite(RFile,header,    sart,'A1');
xlswrite(RFile,ArterialAV,sart,'A2');
xlswrite(RFile,header,    sall,'A1');
xlswrite(RFile,AllRoadsAV,sall,'A2');

Freeway24(6,2:9) = sum(Freeway24(:,2:9)); % Results for 24 h
Arterial24(6,2:9) = sum(Arterial24(:,2:9));
AllRoads24(6,2:9) = sum(AllRoads24(:,2:9));
xlswrite(RFile,head24,       'SuSt','A1');
xlswrite(RFile,Freeway24,    'SuSt','A3');
xlswrite(RFile,Arterial24,   'SuSt','A10');
xlswrite(RFile,AllRoads24,   'SuSt','A17');
xlswrite(RFile,{'Freeways'}, 'SuSt','A2');
xlswrite(RFile,colu24,       'SuSt','A3');
xlswrite(RFile,{'Arterials'},'SuSt','A9');
xlswrite(RFile,colu24,       'SuSt','A10');
xlswrite(RFile,{'All Roads'},'SuSt','A16');
xlswrite(RFile,colu24,       'SuSt','A17');


toc
fprintf('\n** Done aggregating emissions over 24 h by vehicle category and road type **\n');

diary off
