function createfigure(ymatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 21-May-2014 10:12:21

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'YTickLabel',{'','0','1','11','12','13','14','15','16','21','22','23','24','25','27','28','29','30','33','35','37','38','39','40','24'},...
    'YTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24],...
    'XTick',[-14 -13 -12 -11 -10 -9 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16],...
    'FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-14 16]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 24]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Horizontal','on','Parent',axes1);
set(bar1(1),'DisplayName','NOx (Winter Mean Vs Night-1/AM)');
set(bar1(2),'DisplayName','NOx (Winter Mean Vs Midday/PM)');
set(bar1(3),'DisplayName','NOx (Winter Mean Vs Night-2)');
set(bar1(4),'DisplayName','PM (Winter Mean Vs Night-1/AM)');
set(bar1(5),'DisplayName','PM (Winter Mean Vs Midday/PM)');
set(bar1(6),'DisplayName','PM (Winter Mean Vs Night-2)');

% Create xlabel
xlabel('Percent Change','FontSize',16);

% Create ylabel
ylabel('Operating Mode','FontSize',16);

% Create title
title('Winter NOx Emission Rate Comparison for Passenger Cars',...
    'FontSize',20);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[0.6742 0.6975 0.2046 0.1749]);

