function createfigure_speed(xdata1, ydata1, zdata1, strFilePath, strTitle)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 04-Apr-2011 16:08:35

% Create figure
figure1 = figure('Colormap',...
    [0.8471 0.1608 0;0.8689 0.1378 0;0.8908 0.1148 0;0.9126 0.09188 0;0.9345 0.06891 0;0.9563 0.04594 0;0.9782 0.02297 0;1 0 0;1 0.0625 0;1 0.125 0;1 0.1875 0;1 0.25 0;1 0.3125 0;1 0.375 0;1 0.4375 0;1 0.5 0;1 0.5625 0;1 0.625 0;1 0.6875 0;1 0.75 0;1 0.8125 0;1 0.875 0;1 0.9375 0;1 1 0;0.9375 1 0.0625;0.875 1 0.125;0.8125 1 0.1875;0.75 1 0.25;0.6875 1 0.3125;0.625 1 0.375;0.5625 1 0.4375;0.5 1 0.5;0.4375 1 0.5625;0.375 1 0.625;0.3125 1 0.6875;0.25 1 0.75;0.1875 1 0.8125;0.125 1 0.875;0.0625 1 0.9375;0 1 1;0 0.9375 1;0 0.875 1;0 0.8125 1;0 0.75 1;0 0.6875 1;0 0.625 1;0 0.5625 1;0 0.5 1;0 0.4375 1;0 0.375 1;0 0.3125 1;0 0.25 1;0 0.1875 1;0 0.125 1;0 0.0625 1;0 0 1;0.004902 0.01765 0.927;0.009804 0.03529 0.8539;0.01471 0.05294 0.7809;0.01961 0.07059 0.7078;0.02451 0.08824 0.6348;0.02941 0.1059 0.5618;0.03431 0.1235 0.4887;0.03922 0.1412 0.4157]);

% Create axes
axes1 = axes('Parent',figure1,'FontName','Times New Roman',...
    'CLim',[0.0 80.0]);
% Uncomment the following line to preserve the X-limits of the axes
xlim([0 288]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim([0 54]);

view([0 90]);
box('on');
grid('on');
hold('all');

% Create mesh
mesh(xdata1,ydata1,zdata1,'Parent',axes1);

% Create xlabel
xlabel('Time 00:00 ~ 24:00','VerticalAlignment','cap',...
    'HorizontalAlignment','center');

% Create ylabel
ylabel('Postmile (miles)','VerticalAlignment','bottom','Rotation',90,...
    'HorizontalAlignment','center');

% Create title
title(sprintf('%s',strTitle));

% Create colorbar
colorbar('peer',axes1,'FontName','Times New Roman');

if ( length(strFilePath) )
    set(1, 'PaperPositionMode', 'auto');
    filePath = sprintf('%s', strFilePath);
    saveas(figure1, filePath, 'jpg');
end

close(figure1);