function createfigure_flow(xdata1, ydata1, zdata1, strFilePath, strTitle)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 04-Apr-2011 16:08:35

% Create figure
figure1 = figure('Colormap',...
    [0.07843 0.1686 0.549;0.06723 0.1445 0.6134;0.05602 0.1204 0.6779;0.04482 0.09636 0.7423;0.03361 0.07227 0.8067;0.02241 0.04818 0.8711;0.0112 0.02409 0.9356;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 0.9375;0.125 1 0.875;0.1875 1 0.8125;0.25 1 0.75;0.3125 1 0.6875;0.375 1 0.625;0.4375 1 0.5625;0.5 1 0.5;0.5625 1 0.4375;0.625 1 0.375;0.6875 1 0.3125;0.75 1 0.25;0.8125 1 0.1875;0.875 1 0.125;0.9375 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9809 0.0201 0;0.9618 0.0402 0;0.9426 0.06029 0;0.9235 0.08039 0;0.9044 0.1005 0;0.8853 0.1206 0;0.8662 0.1407 0;0.8471 0.1608 0]);

% Create axes
axes1 = axes('Parent',figure1,'FontName','Times New Roman','CLim',[0 1000]);

% Uncomment the following line to preserve the X-limits of the axes
xlim([0 288]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim([0 54]);

view([0 90]);
box('on');
grid('on');
hold('all');

% Create mesh
mesh(xdata1,ydata1,zdata1,'Parent',axes1);

% Create xlabel
xlabel('Time 00:00 ~ 24:00','VerticalAlignment','cap',...
    'HorizontalAlignment','center');

% Create ylabel
ylabel('Postmile (miles)','VerticalAlignment','bottom','Rotation',90,...
    'HorizontalAlignment','center');

% Create title
title(sprintf('%s',strTitle));

% Create colorbar
colorbar('peer',axes1,'FontName','Times New Roman');


if ( length(strFilePath) )
    set(1, 'PaperPositionMode', 'auto');
    filePath = sprintf('%s', strFilePath);
    saveas(figure1, filePath, 'jpg');
end

close(figure1);