function createfigure(xdata1, ydata1, zdata1, X1, Y1)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1,X1,Y1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 02-Nov-2010 02:44:51

% Create figure
figure1 = figure('Name','710 NB');

% Create axes
axes1 = axes('Parent',figure1,...
    'YTickLabel',{'[7.17] Long Beach','[8.33] Atlantic','[9.14] Alondra','[9.42] Compton','[9.94] Rosecrans-1','[10.14] Rosecrans-2','[10.34] S of 105','[10.94] King-1','[11.14] From Rt 105','[11.54] King-2','[11.907] Imperial-1','[12.057] Imperial-2','[13.427] Firestone-1','[13.517] Firestone-2','[14.767] Florence-2','[17.147] Atlantic-2','[17.157] Washington','[18.167] S of 5','[18.507] Olympic','[18.714] Eastern','[19.437] Third'},...
    'YTick',[7.17 8.33 9.14 9.42 9.94 10.14 10.34 10.94 11.14 11.54 11.907 12.057 13.427 13.517 14.767 17.147 17.157 18.167 18.507 18.714 19.437],...
    'XTick',[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24],...
    'Layer','top',...
    'FontWeight','bold',...
    'FontSize',5,...
    'FontName','Arial',...
    'CLim',[0 100]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 24]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[7.17 19.437]);
box(axes1,'on');
hold(axes1,'all');

% Create contour
contour(xdata1,ydata1,zdata1,'LineColor',[0 0 0],...
    'LevelList',[1.6 8.38181818181818 15.1636363636364 21.9454545454545 28.7272727272727 35.5090909090909 42.2909090909091 49.0727272727273 55.8545454545455 62.6363636363636 69.4181818181818],...
    'Fill','on',...
    'Parent',axes1);

% Create plot
plot(X1,Y1,'Parent',axes1,'MarkerFaceColor',[0 0 0],'Marker','o',...
    'LineWidth',2,...
    'LineStyle','none',...
    'Color',[1 0 0]);

% Create xlabel
xlabel('Hour');

% Create ylabel
ylabel('Postmile');

% Create colorbar
colorbar('peer',axes1,'FontWeight','bold','FontSize',5,'FontName','Arial');

